micronaut:
  application:
    name: micronautExemplar
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:mysql://localhost:3306/
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
    username: root
    password: test

netty:
  default:
    allocator:
      max-order: 3

jackson:
  property-naming-strategy: SNAKE_CASE
